name    'postfix'
version '0.1.0'
source 'https://stash.moo.umd.edu/projects/TIM/repos/puppet-postfix/'
author 'Tim Hammond <hammondt@umd.edu>'
license 'Apache License, Version 2.0'
summary 'Basic Postfix module'
description 'Configures postfix to send mail locally'
project_page 'https://stash.moo.umd.edu/projects/TIM/repos/puppet-postfix/'
issues_url 'https://jira.moo.umd.edu'
